services:

  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - database_data:/var/lib/mysql
    env_file:
      - .docker.env
    networks:
      - gateway

  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./docker/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:3000:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`web.localhost`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
    networks:
      - gateway

  php:
#    image: php:8.2-fpm-alpine
    build:
      context: .
      dockerfile: php.Dockerfile
    restart: unless-stopped
    user: 1000:1000
    depends_on:
      - database
    volumes:
      - ./app:/app
    networks:
      - gateway

  phpmyadmin:
    image: phpmyadmin:5
    restart: unless-stopped
    depends_on:
      - database
    env_file:
      - .docker.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.localhost`)"
      - "traefik.http.routers.phpmyadmin.entrypoints=web"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"
    networks:
      - gateway

  traefik:
    image: traefik:latest
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - gateway

networks:
  gateway:

volumes:
  database_data:
