---
name: PHPStan
on: push
jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          working_dir: app/
      - name: PHPStan static analysis
        run: "ls -la && ./vendor/bin/phpstan analyse --debug -c phpstan.neon"
